services:
  # Ollama service
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Uncomment the following lines when you want GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  talensinki-gui:
    build: .
    ports:
      # Maps host port 8001 to container port 8000,
      # which means that the GUI is accessible on http://localhost:8001
      # and the Stramlit app uses the port 8000 inside the container
      - "8001:8000" 
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      # Mount your source code for development
      - ./src:/app/src
      # Uncomment if you want to persist data
      # - ./data:/app/data
    command: ["uv", "run", "talensinki-gui"]
    # Uncomment when you add GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
#
# CLI version of your app
  talensinki:
    build: .
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      # Mount your source code for development
      - ./src:/app/src
      # Uncomment if you want to persist data
      # - ./data:/app/data
    # Keep the container running and provide an interactive terminal
    stdin_open: true
    tty: true
    command: ["uv", "run", "talensinki"]
    # Uncomment when you add GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]


volumes:
  ollama_data:
